' Define constants for Word                                                                                                                                                                                                                               
Const wdTableFormatGrid = 1                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                          
' Create Word application object                                                                                                                                                                                                                          
Set objWord = CreateObject("Word.Application")                                                                                                                                                                                                            
                                                                                                                                                                                                                                                          
' Set the path of the Word document                                                                                                                                                                                                                       
wordDocPath = "J:\BACPAC\Statistics\Special_Projects\DataDictionaryPracticum\dictionary_input\Practicum_BP00XX_Analysis Dataset and Data Dictionary Creation.docx"                                                                                        
' Set the name of the bookmark                                                                                                                                                                                                                            
bookmarkName = "c2c"                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                          
' Set the path for the CSV file                                                                                                                                                                                                                           
csvFilePath = "J:\BACPAC\Statistics\Special_Projects\DataDictionaryPracticum\c2c.csv"                                                                                                                                                                     
                                                                                                                                                                                                                                                          
' Open the Word document                                                                                                                                                                                                                                  
Set objDoc = objWord.Documents.Open(wordDocPath)                                                                                                                                                                                                          
                                                                                                                                                                                                                                                          
' Get the bookmarked range                                                                                                                                                                                                                                
Set objRange = objDoc.Bookmarks(bookmarkName).Range                                                                                                                                                                                                       
                                                                                                                                                                                                                                                          
' Create a file system object for writing CSV                                                                                                                                                                                                             
Set fso = CreateObject("Scripting.FileSystemObject")                                                                                                                                                                                                      
Set csvFile = fso.CreateTextFile(csvFilePath, True)                                                                                                                                                                                                       
                                                                                                                                                                                                                                                          
' Check if the bookmark range contains a table                                                                                                                                                                                                            
If objRange.Tables.Count > 0 Then                                                                                                                                                                                                                         
    ' Get the first table in the bookmark range                                                                                                                                                                                                           
    Set objTable = objRange.Tables(1)                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                          
    ' Copy table data to the CSV file                                                                                                                                                                                                                     
    For i = 1 To objTable.Rows.Count                                                                                                                                                                                                                      
        line = ""                                                                                                                                                                                                                                         
        For j = 1 To objTable.Columns.Count                                                                                                                                                                                                               
            ' Get the cell text, trimming the end-of-cell markers                                                                                                                                                                                         
            cellText = objTable.Cell(i, j).Range.Text                                                                                                                                                                                                     
            cellText = Left(cellText, Len(cellText) - 2) ' Remove end-of-cell markers                                                                                                                                                                     
                                                                                                                                                                                                                                                          
            ' Replace various types of line breaks and special characters                                                                                                                                                                                 
            cellText = Replace(cellText, Chr(13) & Chr(13), "@@") ' Multiple carriage returns                                                                                                                                                             
            cellText = Replace(cellText, Chr(13), "@@")           ' Carriage return                                                                                                                                                                       
            cellText = Replace(cellText, Chr(10), "@@")           ' Line feed                                                                                                                                                                             
            cellText = Replace(cellText, Chr(11), "@@")           ' Vertical tab                                                                                                                                                                          
            cellText = Replace(cellText, Chr(12), "@@")           ' Form feed                                                                                                                                                                             
            cellText = Replace(cellText, Chr(160), "@@")          ' Non-breaking space                                                                                                                                                                    
            ' cellText = Replace(cellText, Chr(59), "@@")           ' Semi-colon                                                                                                                                                                          
            cellText = Replace(cellText, Chr(124), "@@")          ' Vertical bar                                                                                                                                                                          
                                                                                                                                                                                                                                                          
            ' Trim any leading or trailing whitespace                                                                                                                                                                                                     
            cellText = Trim(cellText)                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                          
            ' Escape quotes and commas                                                                                                                                                                                                                    
            cellText = Replace(cellText, """", """""")                                                                                                                                                                                                    
            If InStr(cellText, ",") > 0 Or InStr(cellText, """") > 0 Then                                                                                                                                                                                 
                cellText = """" & cellText & """"                                                                                                                                                                                                         
            End If                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                          
            ' Add cell text to the line                                                                                                                                                                                                                   
            line = line & cellText                                                                                                                                                                                                                        
            If j < objTable.Columns.Count Then                                                                                                                                                                                                            
                line = line & "," ' Comma delimiter                                                                                                                                                                                                       
            End If                                                                                                                                                                                                                                        
        Next                                                                                                                                                                                                                                              
        ' Write line to CSV file                                                                                                                                                                                                                          
        csvFile.WriteLine line                                                                                                                                                                                                                            
    Next                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                          
    ' Inform the user                                                                                                                                                                                                                                     
    MsgBox "Table copied successfully to CSV!", vbInformation                                                                                                                                                                                             
                                                                                                                                                                                                                                                          
Else                                                                                                                                                                                                                                                      
    ' Inform the user if no table is found in the bookmark                                                                                                                                                                                                
    MsgBox "No table found in the specified bookmark.", vbExclamation                                                                                                                                                                                     
End If                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                          
' Close the Word document                                                                                                                                                                                                                                 
objDoc.Close False                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                          
' Quit Word application                                                                                                                                                                                                                                   
objWord.Quit                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                          
' Clean up                                                                                                                                                                                                                                                
Set objTable = Nothing                                                                                                                                                                                                                                    
Set objRange = Nothing                                                                                                                                                                                                                                    
Set objDoc = Nothing                                                                                                                                                                                                                                      
Set objWord = Nothing                                                                                                                                                                                                                                     
csvFile.Close                                                                                                                                                                                                                                             
Set fso = Nothing                                                                                                                                                                                                                                         
Set csvFile = Nothing                                                                                                                                                                                                                                     
