bRecursive = False                                                                                                                                                                                                                                        
sFolder = "J:\BACPAC\SC\kedupug\BP0048\dictionary_input"                                                                                                                                                                                                  
Set oFSO = CreateObject("Scripting.FileSystemObject")                                                                                                                                                                                                     
Set oWord = CreateObject("Word.Application")                                                                                                                                                                                                              
oWord.Visible = True                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                          
Set oFolder = oFSO.GetFolder(sFolder)                                                                                                                                                                                                                     
ConvertFolder(oFolder)                                                                                                                                                                                                                                    
oWord.Quit                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                          
Sub ConvertFolder(oFldr)                                                                                                                                                                                                                                  
  For Each oFile In oFldr.Files                                                                                                                                                                                                                           
    If LCase(oFSO.GetExtensionName(oFile.Name)) = "rtf" Then                                                                                                                                                                                              
        Set oDoc = oWord.Documents.Open(oFile.path)                                                                                                                                                                                                       
        Str = left(oFile,instr(1,oFile,".")-1)                                                                                                                                                                                                            
                                                                                                                                                                                                                                                          
        Dim parentFolder, baseFileName, newPath                                                                                                                                                                                                           
                                                                                                                                                                                                                                                          
        parentFolder = oFSO.GetParentFolderName(oFile)                                                                                                                                                                                                    
	baseFileName = oFSO.GetBaseName(oFile)                                                                                                                                                                                                                   
	                                                                                                                                                                                                                                                         
	parentFolder = "J:\BACPAC\SC\kedupug\BP0048\dictionary_input"                                                                                                                                                                                            
	                                                                                                                                                                                                                                                         
	newPath = oFSO.BuildPath(parentFolder, baseFileName & ".pdf")                                                                                                                                                                                            
                                                                                                                                                                                                                                                          
        oWord.ActiveDocument.SaveAs newPath, 17                                                                                                                                                                                                           
        oDoc.Close                                                                                                                                                                                                                                        
    End If                                                                                                                                                                                                                                                
Next                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                          
If bRecursive Then                                                                                                                                                                                                                                        
    For Each oSubfolder In oFldr.Subfolders                                                                                                                                                                                                               
        ConvertFolder oSubfolder                                                                                                                                                                                                                          
    Next                                                                                                                                                                                                                                                  
End If                                                                                                                                                                                                                                                    
End Sub                                                                                                                                                                                                                                                   
